config/routes.rb
Rails.application.routes.draw do
  
  post 'login', to: 'sessions#create', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'home', to: 'home#show'
  get 'dashboard', to: 'dashboard#show'
  patch 'create_password', to: 'password#create'
  get 'new_password', to: 'password#new'

  root to: "home#show"
end

app/models/user.rb
class User < ActiveRecord::Base
	include BCrypt
	has_secure_password

	def self.find_or_create_from_auth_hash(auth)
		user = where(email: auth.info.email).first
		return user if user
		User.new.tap do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.first_name = auth.info.first_name
			user.last_name = auth.info.last_name
			user.email = auth.info.email
			user.password = auth.uid
			user.save!
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def authenticate
  	redirect_to :login unless user_signed_in?
  end

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
  	!!current_user
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
  	redirect_to :home unless user_signed_in?
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController
	def create
		@user = current_user
		@user.password = params[:user][:password]
		if @user.save
			redirect_to :dashboard 
			return
		end
		redirect_to root_path
	end

	def new
		@user = current_user
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
	def create
		if social_auth_login
			@user = User.find_or_create_from_auth_hash(env["omniauth.auth"])
		elsif params[:session]
			@user = User.find_by(email: params[:session][:email].downcase)
			@user = nil unless @user && @user.authenticate(params[:session][:password])
		end

		unless @user
			redirect_to root_path
			return
		end
		session[:user_id] = @user.id
		return if password_needed?
		redirect_to :dashboard
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end

	private

		def social_auth_login
			env["omniauth.auth"]
		end

		def password_needed?
			if @user.authenticate @user.uid
				redirect_to new_password_path
				return true
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/views/dashboard/show.html.erb
<div class="container">
	<br>
	<row>
		<a href="/logout"><button type="button" class="btn btn-info">Logout</button></a>
	</row>
	<br>
	<row>
		<div class="col-lg-6 col-xs-12 dark">
			<h4 align="center">Patient</h4>
			<form onsubmit="createPatient()" action="#">
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			      <input class="form-control" id="inputPatientName" placeholder="Name">
			    </div>
			  </div>
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			      <input class="form-control" id="inputPatientPhone" placeholder="Phone Number">
			    </div>
			  </div>
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			      <button type="submit" class="btn btn-primary">Submit</button>
			    </div>
			  </div>
			</form>
		</div>
		<div class="col-lg-6 col-xs-12 light">
			<h4 align="center">Doctor</h4>
			<form onsubmit="createDoctor()" action="#">
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			      <input class="form-control" id="inputDoctorName" placeholder="Name">
			    </div>
			  </div>
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			      <input class="form-control" id="inputDoctorPhone" placeholder="Phone Number">
			    </div>
			  </div>
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			      <input class="form-control" id="inputDoctorSpecialization" placeholder="Specialization">
			    </div>
			  </div>
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			      <button type="submit" class="btn btn-primary">Submit</button>
			    </div>
			  </div>
			</form>
		</div>
	</row>
	<row>
		<div class="col-lg-6 col-xs-12 light">
			<h4 align="center">Appointment</h4>
			<form onsubmit="createAppointment()" action="#">
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			    	<input type="hidden" id="doctorId"/>
			    	<input class="form-control" id="inputDoctor" placeholder="Doctor Name" autocomplete="true">
			    </div>
			  </div>
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			    	<input type="hidden" id="patientId"/>
			    	<input class="form-control" id="inputPatient" placeholder="Patient Name" autocomplete="true">
			    </div>
			  </div>
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			      <input class="form-control" id="inputDisease" placeholder="Disease">
			    </div>
			  </div>
			  <div class="form-group row">
			    <div class="col-sm-8 col-sm-offset-2">
			      <button type="submit" class="btn btn-primary">Submit</button>
			    </div>
			  </div>
			</form>
		</div>
		<div class="col-lg-6 col-xs-12 light">
			<h4 align="center">View Appointment</h4>
			<table id="appointmentTable" class="table">
			  <thead>
			    <tr>
			      <th scope="col">Patient Name</th>
			      <th scope="col">Doctor Name</th>
			      <th scope="col">Disease</th>
			    </tr>
			  </thead>
			  <tbody>
			  </tbody>
			</table>
		</div>
	</row>
<div>

app/views/home/show.html.erb
<div class="container">
    <div class="omb_login">
    	<h3 class="omb_authTitle">Continue With</h3>
		<div class="row omb_row-sm-offset-3 omb_socialButtons">
    	    <div class="col-xs-6 col-sm-3">
		        <a href="/auth/facebook" class="btn btn-lg btn-block omb_btn-facebook">
			        <i class="fa fa-facebook visible-xs"></i>
			        <span class="hidden-xs">Facebook</span>
		        </a>
	        </div>
        	<div class="col-xs-6 col-sm-3">
		        <a href="/auth/google_oauth2" class="btn btn-lg btn-block omb_btn-google">
			        <i class="fa fa-google-plus visible-xs"></i>
			        <span class="hidden-xs">Google+</span>
		        </a>
	        </div>	
		</div>

		<div class="row omb_row-sm-offset-3 omb_loginOr">
			<div class="col-xs-12 col-sm-6">
				<hr class="omb_hrOr">
				<span class="omb_spanOr">or</span>
			</div>
		</div>

		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-6">	
			    <%= form_for(:session, url: login_path) do |f| %>
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-user"></i></span>
						<%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
					</div>
					<span class="help-block"></span>
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-lock"></i></span>
					    <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
					</div>
					<br>
			      <%= f.submit "Log in", class: "btn btn-lg btn-primary btn-block" %>
			    <% end %>

			</div>
    	</div>
	</div>



        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mdoctor</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<link href="https://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" rel="Stylesheet"></link>
	<script src="https://code.jquery.com/ui/1.10.2/jquery-ui.js" ></script>

	<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="Stylesheet"></link>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" ></script>

	<link href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/password/new.html.erb
<div class="container">
    <div class="omb_login">
		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-6">
				<br>	
			    <%= form_for(@user, url: create_password_path) do |f| %>
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-lock"></i></span>
					    <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
					</div>
					<br>
			      <%= f.submit "Update Password", class: "btn btn-lg btn-primary btn-block" %>
			    <% end %>
			</div>
    	</div>
	</div>
</div>